openapi: 3.0.0
info:
  title: Movie api
  description: This API provides the details of the movie.
  version: 3.0.0
servers:
  - url: /movie/v3
paths:
  /movies:
    get:
      summary: Returns a list movie.
      operationId: controller.get_movies
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'

  /movies/{director_name}:
    parameters:
    - name: director_name
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns a list of movies that this director has directed.
      operationId: controller.get_movies_directed_by_director_name
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Movie'
          links:
            score:
              operationId: controller.get_average_score_for_director
              parameters:
                director_name: $response.body#/director_name
  
  /movies/{title_year}:
    parameters:
    - name: title_year
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns full detail of the movies that have this title.
      operationId: controller.get_movie_by_year
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Movie'
          links:
            year-Score:
              operationId: controller.get_average_score_of_movies_in_that_year
              parameters:
                title_year: $response.body#/title_year
            EachDirectorScore:
              operationId: controller.get_average_score_for_each_director_in_each_year
              parameters:
                title_year: $response.body#/title_year
  /movies/{movie_title}:
    parameters:
    - name: movie_title
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns full detail of the movies that have this title.
      operationId: controller.get_movie_detail_by_movie_title
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Movie'
  /movies/{title_year}/year-score:
    parameters:
    - name: title_year
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns full detail of the movies that have this title.
      operationId: controller.get_average_score_of_movies_in_that_year
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  type: number
  /movies/{director_name}/score:
    parameters:
    - name: director_name
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns average score of all movie of this director.
      operationId: controller.get_average_score_for_director
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: number
  /movies/best-movies:
    get:
      summary: Returns a list movie that ahve imdb scor more than 9.5.
      operationId: controller.get_best_movies
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
  /movies/EachYearScore:
    get:
      summary: Returns a list movie.
      operationId: controller.get_average_score_of_movies_in_each_year
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageEachYear'
  /movies/MostYearScore:
    get:
      summary: Returns a list movie.
      operationId: controller.find_most_score_of_year
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
  /movies/EachDirectorScore:
    get:
      summary: Returns a list movie.
      operationId: controller.get_average_score_for_each_director
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Director'
  /movies/BestDirector:
    get:
      summary: Returns a list movie.
      operationId: controller.get_best_director
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
  # /movies/{title_year}/EachDirectorScore/:
  #   - name: title_year
  #     in: path
  #     required: true
  #     schema:
  #       type : integer
  #   get:
  #     summary: Returns a list movie.
  #     operationId: controller.get_average_score_for_each_director_in_each_year
  #     responses:
  #       200:
  #         description: Success
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/Director'
  /movies/{actor_name}:
    parameters:
    - name: actor_name
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns a list of movies that this director has directed.
      operationId: controller.get_movies_from_actor
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
          links:
            all-score:
              operationId: controller.get_average_score_of_actor
              parameters:
                actor_1_name: $response.body#/actor_name
  /movies/{actor_name}/all-score:
    parameters:
    - name: actor_name
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns average score of all movie of this director.
      operationId: controller.get_average_score_of_actor
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array 
                $ref: '#/components/schemas/Actor'
          
components:
  schemas:
    Movie:
      type: object
      properties:
        director_name:
          type: string
        duration:
          type: string
        actor_2_name:
          type: string
        genres:
          type: string
        actor_1_name:
          type: string
        movie_title:
          type: string
        num_voted_user:
          type: integer
        actor_3_name:
          type: string
        movie_imdb_link:
          type: string
        num_user_for_reviews:
          type: integer
        language:
          type: string
        country:
          type: string
        title_year:
          type: integer
        imdb_score:
          type: number
          format: float
    AverageEachYear:
      type: object
      properties:
        title_year:
          type: integer
        imdb_avg_score:
          type: number
          format: float
    Director:
      type: object
      properties:
        director_name:
          type: string
        imdb_avg_score:
          type: number
          format: float
    Actor:
      type: object
      properties:
        director_name:
          type: string
        imdb_avg_score:
          type: number
          format: float
    
