# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AverageEachYear(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title_year=None, imdb_avg_score=None):  # noqa: E501
        """AverageEachYear - a model defined in OpenAPI

        :param title_year: The title_year of this AverageEachYear.  # noqa: E501
        :type title_year: int
        :param imdb_avg_score: The imdb_avg_score of this AverageEachYear.  # noqa: E501
        :type imdb_avg_score: float
        """
        self.openapi_types = {
            'title_year': int,
            'imdb_avg_score': float
        }

        self.attribute_map = {
            'title_year': 'title_year',
            'imdb_avg_score': 'imdb_avg_score'
        }

        self._title_year = title_year
        self._imdb_avg_score = imdb_avg_score

    @classmethod
    def from_dict(cls, dikt) -> 'AverageEachYear':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AverageEachYear of this AverageEachYear.  # noqa: E501
        :rtype: AverageEachYear
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title_year(self):
        """Gets the title_year of this AverageEachYear.


        :return: The title_year of this AverageEachYear.
        :rtype: int
        """
        return self._title_year

    @title_year.setter
    def title_year(self, title_year):
        """Sets the title_year of this AverageEachYear.


        :param title_year: The title_year of this AverageEachYear.
        :type title_year: int
        """

        self._title_year = title_year

    @property
    def imdb_avg_score(self):
        """Gets the imdb_avg_score of this AverageEachYear.


        :return: The imdb_avg_score of this AverageEachYear.
        :rtype: float
        """
        return self._imdb_avg_score

    @imdb_avg_score.setter
    def imdb_avg_score(self, imdb_avg_score):
        """Sets the imdb_avg_score of this AverageEachYear.


        :param imdb_avg_score: The imdb_avg_score of this AverageEachYear.
        :type imdb_avg_score: float
        """

        self._imdb_avg_score = imdb_avg_score
